### ISSUE TITLE
Windows Wallet: Confirmed transactions but balance remains at Zero.

### ISSUE THREAD

**Issue by pau1phi11ips** [coinbarn/coinbarn-extension#15]
I have sent some Ergo to the Coinbarn address. They all show on the coin explorer with over 100 confirmations.

The transactions show in the tab in the Coinbarn wallet however Account Balance says 0 and I can send them on to a different address.

Also the address I got from the wallet is 80 characters long which was a bit confusing as all the other addresses I've seen are 51 characters long? It appears valid though as it does show on the explorer.

**Comment by char543** [comment]
Exact same issue here on macOS 10.14.6, Wallet version 0.1.0

Ergo shows as confirmed under transactions and on explorer, Account balance remains at 0.

**Comment by ladopixel** [comment]
The same on MacOS 10.15.7 with v. 0.1.0
Can the seed phrase be imported into another wallet? In which?
<img width="324" alt="Wallet coinbarn mage" src="https://user-images.githubusercontent.com/1231955/108279433-75e1ca80-7131-11eb-8edb-5e444f70582b.png">

**Comment by pau1phi11ips** [comment]
Found the answer, you need to wait for 720 confirmations before the balance gets updated for a reward address instead of the standard 100.

https://www.ergoforum.org/t/q-a-on-mining-for-pool-operators-and-solo-miners/587
